# ASCP BOC {-}

ASCP BOC's Content Guideline for the Technologist in Hematology, H(ASCP), and the Specialist in Hematology, SH(ASCP), certification exams consists of five major content areas. The information below was last revised on ASCP's website October 2023

## **Hematology Physiology** {-}

**Exam Percentage:** 10% - 15%

**Description:** Physiology (production, destruction, and function) of blood, body fluids, and bone marrow

## **Hematology Disease States** {-}

**Exam Percentage:** 20% - 25%

**Description:** Disease states associated with qualitative/quantitative abnormalities of erythrocytes, leukocytes, and platelets

## **Hematology Laboratory Testing** {-}

**Exam Percentage:** 20% - 25%

**Description:** Cell counts, differentials/morphology evaluation, hemoglobin/hematocrit, indices, hemolytic indicators, special stains, flow cytometry immunophenotyping, molecular/cytogenetic testing

## **Hemostasis** {-}

**Exam Percentage:** 20% - 25%

**Description:** Physiology (pathways and vascular system), hemostasis-related disease states, hemostasis laboratory determinations

## **Laboratory Operations** {-}

**Exam Percentage:** 15% - 20%

**Description:** Quality assessment/troubleshooting, point-of-care testing (POCT), regulations, safety, laboratory mathematics, instrumentation, and laboratory administration (SH ONLY)
